# Generated by Django 4.2.11 on 2024-04-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('set_active', 'Can active users'), ('change_description', 'Can change description'), ('change_category', 'Can change category')]},
        ),
    ]
