# Generated by Django 4.2.11 on 2024-04-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_client_mailinglog_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='patronymic',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Фамилия'),
        ),
    ]
