# Generated by Django 4.2.11 on 2024-04-10 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0008_client_owner_mailinglog_mailing_mailinglog_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 10, 18, 40, 32, 362707, tzinfo=datetime.timezone.utc), verbose_name='Дата конца рассылки'),
            preserve_default=False,
        ),
    ]
