# Generated by Django 4.2.11 on 2024-04-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0009_mailingsettings_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglog',
            name='owner',
        ),
    ]
