# Generated by Django 4.2.11 on 2024-04-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0011_alter_mailingsettings_options_mailinglog_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('set_active', 'Can active users')], 'verbose_name': 'Настройки рассылки', 'verbose_name_plural': 'Настройки рассылки'},
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус работы'),
        ),
    ]
