# Generated by Django 4.2.11 on 2024-04-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0012_alter_mailingsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('set_active', 'Can active mailingsettings')], 'verbose_name': 'Настройки рассылки', 'verbose_name_plural': 'Настройки рассылки'},
        ),
    ]
