# Generated by Django 4.2.11 on 2024-04-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0013_alter_mailingsettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglog',
            options={'ordering': ('-time',), 'verbose_name': 'лог', 'verbose_name_plural': 'логи'},
        ),
    ]
